# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', '-date']},
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
    ]
