# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180620_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='short_disc',
        ),
        migrations.AddField(
            model_name='book',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание тега'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='электронная почта автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=60, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=60, verbose_name='отчество автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=60, verbose_name='фамилия автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.ImageField(blank=True, upload_to='', verbose_name='обложка книги'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=30, verbose_name='имя тега'),
        ),
    ]
