# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180620_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='short_desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(help_text='Укажите тег для этой книги', to='mainapp.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя тега'),
        ),
    ]
