# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180620_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_desc',
            field=models.TextField(blank=True, max_length=3000, verbose_name='краткое описание'),
        ),
    ]
