# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180620_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='active_flag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
