# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180620_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
